utils:
  staffPermission: 'skycloud.staff'
  showServersWithoutStaff: true

messages:
  header: '&5&l<!> &dOnline Staff &7({players} players online)'
  serverLine: '&6&l➦ &e&l{server} &7({players}/{maxPlayers})'
  staffLine: ' &f» {prefix}{player} &7[&a{time}&7]'
  noStaffLine: ' &cNo staff is online.'
  hideLine: '&5&l<!> &dYou have &f{mode} &dyour staff list visibility.'
  noStaffOnlineLine: ' &cThere are currently no members of staff to display.'

servers:
  - hub-1
  - hub-2
  - atlas-1