utils:
  noPerm: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
  staffPermission: 'skycloud.staff'
  adminPermission: 'skycloud.admin'
  showServersWithoutStaff: true

staffCommand:
  header: '&5&l<!> &dOnline Staff &7({players}/{maxPlayers})'
  serverLine: '&6&l➦ &e&l{server} &7({players})'
  staffLine: ' &f» {prefix}{player} &7[&a{time}&7]'
  noStaffLine: ' &cNo staff is online.'
  noStaffOnlineLine: ' &cThere are currently no members of staff to display.'

hideCommand:
  hideLine: '&5&l<!> &dYou have &f{mode} &dyour staff list visibility.'

alertsCommand:
  toggle: '&5&l<!> &dYou have &f{mode} &dyour staff alerts.'

staffAlerts:
  connected: '&5&l<!> &f{player} &dhas connected to &e{server}&d.'
  switched: '&5&l<!> &f{player} &dhas moved from &e{oldServer} &dto &e{newServer}&d!'
  disconnected: '&5&l<!> &f{player} &dhas disconnected from &e{server}&d!'

servers:
  - hub-1
  - hub-2
  - atlas-1