utils:
  noPerm: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
  staffPermission: 'skycloud.staff'
  adminPermission: 'skycloud.admin'
  showServersWithoutStaff: true

staffCommand:
  header: '&c&l<!> &dOnline Staff &7({players}/{maxPlayers})'
  serverLine: '&6&l➦ &e&l{server} &7({players})'
  staffLine: ' &f» {prefix}{player} &7[&a{time}&7]'
  noStaffLine: ' &cNo members of staff are online.'
  noStaffOnlineLine: ' &cThere are currently no members of staff on the network.'

staffChat:
  format: '&8(&cSTAFF&8) {rank}{player} &7({server}) &8» &f{content}'
  invalid: '&cUsage: /staffchat <content: String>'

hideCommand:
  hideLine: '&8(&cSTAFF&8) &7You have &c{mode} &7your staff list visibility.'

alertsCommand:
  toggle: '&8(&cSTAFF&8) &7You have &c{mode} &7your staff alerts.'

staffAlerts:
  connected: '&8(&cSTAFF&8) &e{player} &7has connected to &e{server}&7.'
  switched: '&8(&cSTAFF&8) &e{player} &7has moved from &e{oldServer} &7to &e{newServer}&7.'
  disconnected: '&8(&cSTAFF&8) &e{player} &7has disconnected from &e{server}&a.'

servers:
  - hub-1
  - hub-2
  - atlas-1
  - orbit-1